source: .
destination: _site
theme: jekyll-theme-minimal

# SCSS configuration: explicitly set sass_dir to prevent Jekyll from looking for /docs directory
sass:
  sass_dir: _sass
  style: compressed
  load_paths:
    - _sass

github: [metadata]
title: 'UnderZ'
description: 'Javascript Library.'
show_downloads: true
show_menu: true
google_analytics: ''
programmer: ["hlaCk","https://github.com/mPhpMaster"]
repository_url: 'https://github.com/mPhpMaster/UnderZ'
repoZip_url: 'https://github.com/mPhpMaster/UnderZ/zipball/master'
repoTar_url: 'https://github.com/mPhpMaster/UnderZ/tarball/master'
repository: 'mPhpMaster/UnderZ'

collections:
  - UnderZ
